FROM registry.access.redhat.com/ubi9/go-toolset:latest AS builder
WORKDIR /opt/app-root/src
COPY go.mod .
COPY main.go .
COPY static/ static/
RUN go build -o httpd-fileserver main.go

FROM registry.access.redhat.com/ubi9-micro:latest
COPY --from=builder /opt/app-root/src/httpd-fileserver /usr/local/bin/httpd-fileserver
COPY --from=builder /opt/app-root/src/static/ /static/
RUN mkdir -p /data && chown 1001:0 /data && chmod 775 /data
EXPOSE 8080
USER 1001
ENTRYPOINT ["httpd-fileserver"]
