#!/usr/bin/env bash
# deploy.sh — ACM Virtual Machine Management Demo
#
# Deployment order:
#   1. Hub cluster (operators only, Showroom deferred)
#   2. Student clusters (with RHACM auto-import to hub)
#   3. Showroom on hub (with student cluster variables injected)
#   4. Generate student-info.txt
#
# Works with unmodified upstream agd — no -e flag needed.
# Runtime values are merged into generated vars files.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# -----------------------------------------------------------------
# Read config.yml if present (generated by the onboard skill).
# Env vars passed on the command line take precedence.
# -----------------------------------------------------------------
CONFIG_FILE="$SCRIPT_DIR/config.yml"
if [[ -f "$CONFIG_FILE" ]]; then
  while IFS=': ' read -r key value; do
    key=$(echo "$key" | tr -d ' ')
    value=$(echo "$value" | tr -d '"' | tr -d "'")
    [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
    upper_key=$(echo "$key" | tr '[:lower:]' '[:upper:]')
    if [[ -z "${!upper_key:-}" ]]; then
      export "$upper_key=$value"
    fi
  done < "$CONFIG_FILE"
fi

# -----------------------------------------------------------------
# Cross-platform sed helper (GNU vs BSD)
# -----------------------------------------------------------------
sed_inplace() {
  if [[ "$(uname -s)" == "Darwin" ]]; then
    sed -i '' "$@"
  else
    sed -i "$@"
  fi
}

# -----------------------------------------------------------------
# Fail-fast prerequisite checks
# -----------------------------------------------------------------
for cmd in python3 aws sshpass; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "ERROR: '$cmd' is required but not found."
    echo "Run the onboard skill (/onboard) or install it manually."
    exit 1
  fi
done

AGNOSTICD_ROOT="${AGNOSTICD_ROOT:-$HOME/Development/agnosticd-v2}"
VARS_DIR="$AGNOSTICD_ROOT/../agnosticd-v2-vars"
OUTPUT_DIR="$AGNOSTICD_ROOT/../agnosticd-v2-output"

BASE_GUID="${BASE_GUID:-acmvirt}"
HUB_CONFIG="${HUB_CONFIG:-acm-virt-hub}"
STUDENT_TYPE="${STUDENT_TYPE:-sno}"
if [[ "$STUDENT_TYPE" == "sno" ]]; then
  STUDENT_CONFIG_TEMPLATE="${STUDENT_CONFIG_TEMPLATE:-acm-virt-student-sno}"
else
  STUDENT_CONFIG_TEMPLATE="${STUDENT_CONFIG_TEMPLATE:-acm-virt-student}"
fi
ACCOUNT="${ACCOUNT:-sandbox3008}"
NUM_STUDENTS="${NUM_STUDENTS:-1}"
PARALLEL="${PARALLEL:-false}"
MANIFEST="$SCRIPT_DIR/students.txt"

DEPLOY_HUB="${DEPLOY_HUB:-true}"
DEPLOY_SHOWROOM="${DEPLOY_SHOWROOM:-true}"
HUB_GUID="${HUB_GUID:-${BASE_GUID}-hub}"

DEMO_ROOT="${DEMO_ROOT:-$HOME/acm-virt-management-demo}"

# -----------------------------------------------------------------
# Pre-flight: ensure vars symlinks exist so agd finds our configs
# -----------------------------------------------------------------
ensure_symlink() {
  local target="$1" link="$2"
  if [[ -L "$link" ]]; then
    # Remove stale symlinks that don't resolve
    if [[ ! -e "$link" ]]; then
      echo "   Removing broken symlink: $link"
      rm -f "$link"
    else
      return
    fi
  fi
  if [[ -f "$link" ]]; then
    echo "   Backing up $link -> ${link}.bak"
    mv "$link" "${link}.bak"
  fi
  ln -s "$target" "$link"
  echo "   Symlinked $link -> $target"
}

echo "==> Ensuring vars file symlinks (relative for container compatibility)..."
if [[ ! -d "$VARS_DIR" ]]; then
  echo "ERROR: Vars directory not found: $VARS_DIR"
  echo "Run 'make setup' or 'cd $AGNOSTICD_ROOT && ./bin/agd setup' first."
  exit 1
fi
# Compute the relative path from VARS_DIR to SCRIPT_DIR (the agnosticd/ subdir of this repo)
if command -v realpath &>/dev/null; then
  VARS_SUBDIR="$(realpath --relative-to="$VARS_DIR" "$SCRIPT_DIR")"
else
  # Fallback: assume repo is cloned inside VARS_DIR
  VARS_SUBDIR="$(python3 -c "import os.path; print(os.path.relpath('$SCRIPT_DIR', '$VARS_DIR'))")"
fi
ensure_symlink "${VARS_SUBDIR}/acm-virt-hub.yaml" "$VARS_DIR/acm-virt-hub.yml"
if [[ -f "$SCRIPT_DIR/acm-virt-student.yaml" ]]; then
  ensure_symlink "${VARS_SUBDIR}/acm-virt-student.yaml" "$VARS_DIR/acm-virt-student.yml"
fi
ensure_symlink "${VARS_SUBDIR}/acm-virt-student-sno.yaml" "$VARS_DIR/acm-virt-student-sno.yml"
echo ""

# -----------------------------------------------------------------
# Pre-flight: quota check
# -----------------------------------------------------------------
QUOTA_SCRIPT="$DEMO_ROOT/agnosticd/check-quota.sh"
if [[ -x "$QUOTA_SCRIPT" ]]; then
  echo "==> Running AWS quota pre-flight check..."
  if ! AWS_REGION="${AWS_REGION:-us-east-2}" NUM_STUDENTS="$NUM_STUDENTS" "$QUOTA_SCRIPT"; then
    echo ""
    echo "Quota check FAILED. Fix the issues above before deploying."
    echo "Override with SKIP_QUOTA_CHECK=true if you know what you're doing."
    if [[ "${SKIP_QUOTA_CHECK:-false}" != "true" ]]; then
      exit 1
    fi
    echo "SKIP_QUOTA_CHECK is set — proceeding anyway."
  fi
  echo ""
fi

# -----------------------------------------------------------------
# Pre-flight: pull secret
# -----------------------------------------------------------------
PULL_SECRET_FILE="${PULL_SECRET_FILE:-$HOME/pull-secret.json}"
SECRETS_FILE="$AGNOSTICD_ROOT/../agnosticd-v2-secrets/secrets.yml"

if [[ ! -f "$PULL_SECRET_FILE" ]]; then
  echo "ERROR: OpenShift pull secret not found at $PULL_SECRET_FILE"
  echo "Download it from https://console.redhat.com/openshift/downloads"
  exit 1
fi

if grep -q '<Add Your Pull Secret here>' "$SECRETS_FILE" 2>/dev/null; then
  echo "==> Populating ocp4_pull_secret from $PULL_SECRET_FILE ..."
  PULL_SECRET_CONTENT=$(cat "$PULL_SECRET_FILE")
  sed_inplace "s|ocp4_pull_secret: '.*'|ocp4_pull_secret: '${PULL_SECRET_CONTENT}'|" "$SECRETS_FILE"
  echo "   Pull secret injected into $SECRETS_FILE"
  echo ""
fi

# -----------------------------------------------------------------
# Step 1: Deploy hub cluster (skip Showroom — deployed after students)
# -----------------------------------------------------------------
cd "$AGNOSTICD_ROOT"
> "$MANIFEST"

if [[ "$DEPLOY_HUB" == "true" ]]; then
  echo "==> Deploying ACM Hub cluster ($HUB_GUID) ..."
  echo "   Showroom deferred until after student clusters are ready."
  ./bin/agd provision -g "$HUB_GUID" -c "$HUB_CONFIG" -a "$ACCOUNT"
  echo "$HUB_GUID" >> "$MANIFEST"
  echo "Hub cluster deployed (operators ready, Showroom pending)."
  echo ""
fi

# -----------------------------------------------------------------
# Extract hub credentials for student RHACM import
# -----------------------------------------------------------------
HUB_OUTPUT_DIR="$OUTPUT_DIR/$HUB_GUID"
HUB_USER_DATA="$HUB_OUTPUT_DIR/provision-user-data.yaml"

if [[ ! -f "$HUB_USER_DATA" ]]; then
  echo "ERROR: Hub user data not found at $HUB_USER_DATA"
  echo "The hub cluster must be deployed before student clusters."
  exit 1
fi

HUB_API_URL=$(grep 'openshift_api_url:' "$HUB_USER_DATA" | head -1 | awk '{print $2}')
HUB_TOKEN=$(grep 'openshift_cluster_admin_token:' "$HUB_USER_DATA" | head -1 | awk '{print $2}')
HUB_CONSOLE_URL=$(grep 'openshift_console_url:' "$HUB_USER_DATA" | head -1 | awk '{print $2}' || echo "N/A")
HUB_BASTION=$(grep 'bastion_public_hostname:' "$HUB_USER_DATA" | head -1 | awk '{print $2}' || echo "N/A")

echo "==> Hub credentials extracted for student RHACM import."
echo "   Hub API: $HUB_API_URL"
echo ""

# -----------------------------------------------------------------
# Step 2: Deploy student clusters
#   Generates a per-student vars file that merges the template
#   with runtime hub credentials. Works with unmodified agd.
# -----------------------------------------------------------------
deploy_student() {
  local guid="$1"
  local student_num="$2"
  local student_config="${STUDENT_CONFIG_TEMPLATE}-${student_num}"
  local template_file="$SCRIPT_DIR/${STUDENT_CONFIG_TEMPLATE}.yaml"

  {
    cat "$template_file"
    echo ""
    echo "# --- deploy.sh runtime: hub credentials for RHACM import ---"
    echo "ocp4_workload_rhacm_import_hub_api_url: \"$HUB_API_URL\""
    echo "ocp4_workload_rhacm_import_hub_token: \"$HUB_TOKEN\""
    echo "ocp4_workload_rhacm_import_cluster_name: \"student-${student_num}\""
  } > "$VARS_DIR/${student_config}.yml"

  echo "==> Deploying student cluster $student_num ($guid) ..."
  echo "$guid" >> "$MANIFEST"
  ./bin/agd provision -g "$guid" -c "$student_config" -a "$ACCOUNT"

  rm -f "$VARS_DIR/${student_config}.yml"
}

if (( NUM_STUDENTS > 0 )); then
  if [[ "$PARALLEL" == "true" ]]; then
    pids=()
    for i in $(seq 1 "$NUM_STUDENTS"); do
      deploy_student "${BASE_GUID}-s${i}" "$i" &
      pids+=($!)
    done
    for pid in "${pids[@]}"; do wait "$pid"; done
  else
    for i in $(seq 1 "$NUM_STUDENTS"); do
      deploy_student "${BASE_GUID}-s${i}" "$i"
    done
  fi
fi

# -----------------------------------------------------------------
# Step 2b: Post-import fixups on hub cluster
#   - Enable ApplicationSet controller in ArgoCD CR
#   - Install application-manager addon on each student cluster
#     (required for GitOpsCluster to register clusters with ArgoCD)
# -----------------------------------------------------------------
echo "==> Applying post-import fixups on hub..."
HUB_BASTION_HOST=$(grep 'bastion_public_hostname:' "$HUB_USER_DATA" 2>/dev/null | head -1 | awk '{print $2}')
HUB_BASTION_PASS=$(grep 'bastion_ssh_password:' "$HUB_USER_DATA" 2>/dev/null | head -1 | awk '{print $2}')

if [[ -n "$HUB_BASTION_HOST" && -n "$HUB_BASTION_PASS" ]]; then
  sshpass -p "$HUB_BASTION_PASS" ssh -o StrictHostKeyChecking=no "student@${HUB_BASTION_HOST}" bash -s <<'FIXUP_EOF'
# Enable ApplicationSet controller if not already present
if ! oc get deploy openshift-gitops-applicationset-controller -n openshift-gitops &>/dev/null; then
  echo "   Enabling ApplicationSet controller..."
  oc patch argocd openshift-gitops -n openshift-gitops --type=merge \
    -p '{"spec":{"applicationSet":{"enabled":true,"resources":{"limits":{"cpu":"1","memory":"512Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}}}'
fi
FIXUP_EOF

  # Per-student-cluster addons and labels
  for i in $(seq 1 "$NUM_STUDENTS"); do
    echo "   Configuring addons and labels on student-${i}..."
    sshpass -p "$HUB_BASTION_PASS" ssh -o StrictHostKeyChecking=no "student@${HUB_BASTION_HOST}" bash -s <<ADDON_EOF
oc apply -f - <<'EOF'
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: application-manager
  namespace: student-${i}
spec:
  installNamespace: open-cluster-management-agent-addon
---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: governance-policy-framework
  namespace: student-${i}
spec:
  installNamespace: open-cluster-management-agent-addon
---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: config-policy-controller
  namespace: student-${i}
spec:
  installNamespace: open-cluster-management-agent-addon
---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: search-collector
  namespace: student-${i}
spec:
  installNamespace: open-cluster-management-agent-addon
EOF
oc label managedcluster student-${i} acm/cnv-operator-install="true" --overwrite
ADDON_EOF
  done

  # One-time hub-level Fleet Virtualization enablement
  echo "   Enabling Fleet Virtualization on hub..."
  sshpass -p "$HUB_BASTION_PASS" ssh -o StrictHostKeyChecking=no "student@${HUB_BASTION_HOST}" bash -s <<'FLEET_VIRT_EOF'
oc annotate search search-v2-operator -n open-cluster-management \
  virtual-machine-preview='true' --overwrite
oc patch multiclusterhub multiclusterhub -n open-cluster-management \
  --type=merge -p '{"spec":{"overrides":{"components":[{"name":"cnv-mtv-integrations","enabled":true}]}}}'

# Install OpenShift Virtualization operator on hub (for console plugin / fleet VM view)
if ! oc get csv -n openshift-cnv 2>/dev/null | grep -q Succeeded; then
  echo "   Installing OpenShift Virtualization operator on hub..."
  oc create ns openshift-cnv 2>/dev/null || true
  cat <<EOF2 | oc apply -f -
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kubevirt-hyperconverged-group
  namespace: openshift-cnv
spec:
  targetNamespaces:
    - openshift-cnv
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kubevirt-hyperconverged
  source: redhat-operators
  sourceNamespace: openshift-marketplace
EOF2
  echo "   Waiting for CNV operator CSV..."
  for attempt in $(seq 1 60); do
    phase=$(oc get csv -n openshift-cnv -o jsonpath='{.items[0].status.phase}' 2>/dev/null)
    if [ "$phase" = "Succeeded" ]; then break; fi
    if [ "$phase" = "Failed" ] || [ "$attempt" -gt 30 ]; then
      # Scale down non-essential pods that may fail on small workers
      oc scale deploy virt-platform-autopilot -n openshift-cnv --replicas=0 2>/dev/null
      oc scale deploy kubevirt-migration-controller -n openshift-cnv --replicas=0 2>/dev/null
    fi
    sleep 5
  done
  # Create HyperConverged CR
  cat <<EOF2 | oc apply -f -
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  virtualMachineOptions:
    disableFreePageReporting: false
  deployment:
    applicationAwareConfig:
      enable: false
    deployVmConsoleProxy: false
EOF2
  # Enable console plugin (idempotent)
  CURRENT_PLUGINS=$(oc get consoles.operator.openshift.io cluster -o jsonpath='{.spec.plugins[*]}' 2>/dev/null || echo "")
  if ! echo "$CURRENT_PLUGINS" | grep -qw "kubevirt-plugin"; then
    oc patch consoles.operator.openshift.io cluster --type=json \
      -p='[{"op":"add","path":"/spec/plugins/-","value":"kubevirt-plugin"}]' 2>/dev/null
  fi
fi
FLEET_VIRT_EOF

  echo "   Post-import fixups complete."
else
  echo "   WARNING: Could not determine hub bastion — skipping post-import fixups."
  echo "   You will need to manually enable ApplicationSet and install application-manager addon."
fi
echo ""

# -----------------------------------------------------------------
# Step 2b.2: Clone workshop repo to hub bastion
#   Students run `oc apply -f ~/acm-virt-management-demo/policies/...`
#   from the Showroom terminal (which SSH's into the hub bastion).
# -----------------------------------------------------------------
if [[ -n "$HUB_BASTION_HOST" && -n "$HUB_BASTION_PASS" ]]; then
  echo "==> Cloning workshop repo to hub bastion..."
  sshpass -p "$HUB_BASTION_PASS" ssh -o StrictHostKeyChecking=no "student@${HUB_BASTION_HOST}" bash -s <<'CLONE_EOF'
if [ ! -d ~/acm-virt-management-demo ]; then
  git clone https://github.com/tosin2013/acm-virt-management-demo.git ~/acm-virt-management-demo
else
  cd ~/acm-virt-management-demo && git pull --ff-only
fi
CLONE_EOF
  echo "   Workshop repo available at ~/acm-virt-management-demo on hub bastion."
fi
echo ""

# -----------------------------------------------------------------
# Step 2c: Deploy HTTP file server on each student cluster
#   Required for Windows ISO hosting (Module 1 Part 3).
#   Deploys: namespace, PVC, BuildConfig, Deployment with OAuth proxy,
#   Service, and Route.
# -----------------------------------------------------------------
echo "==> Deploying HTTP file server on student clusters..."
for i in $(seq 1 "$NUM_STUDENTS"); do
  s_guid="${BASE_GUID}-s${i}"
  s_user_data="$OUTPUT_DIR/${s_guid}_user_data.yaml"
  S_BASTION_HOST=$(grep 'bastion_public_hostname:' "$s_user_data" 2>/dev/null | head -1 | awk '{print $2}')
  S_BASTION_PASS=$(grep 'bastion_ssh_password:' "$s_user_data" 2>/dev/null | head -1 | awk '{print $2}')

  if [[ -z "$S_BASTION_HOST" || -z "$S_BASTION_PASS" ]]; then
    echo "   WARNING: Could not determine student-${i} bastion — skipping file server deploy."
    continue
  fi

  echo "   Deploying httpd-fileserver on student-${i}..."
  sshpass -p "$S_BASTION_PASS" ssh -o StrictHostKeyChecking=no "student@${S_BASTION_HOST}" bash -s <<'FILESERVER_EOF'
set -e
oc new-project httpd-server 2>/dev/null || oc project httpd-server

# PVC for file storage
oc apply -f - <<'EOF'
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-fileserver-data
  namespace: httpd-server
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: gp3-csi
  resources:
    requests:
      storage: 20Gi
EOF

# ImageStream + BuildConfig
oc apply -f - <<'EOF'
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: httpd-fileserver
  namespace: httpd-server
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: httpd-fileserver
  namespace: httpd-server
spec:
  source:
    type: Git
    git:
      uri: https://github.com/tosin2013/acm-virt-management-demo.git
      ref: main
    contextDir: components/httpd-fileserver
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: httpd-fileserver:latest
  triggers:
    - type: ConfigChange
EOF

# Wait for build to complete
echo "   Waiting for image build..."
sleep 5
BUILD=$(oc get builds -n httpd-server --no-headers -o name | tail -1)
if [[ -n "$BUILD" ]]; then
  oc wait --for=condition=Complete "$BUILD" -n httpd-server --timeout=300s
fi

# ServiceAccount + OAuth secret
oc create sa httpd-fileserver -n httpd-server 2>/dev/null || true
oc annotate sa httpd-fileserver -n httpd-server \
  serviceaccounts.openshift.io/oauth-redirectreference.primary='{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"httpd-server"}}' --overwrite
oc create secret generic httpd-proxy-cookie \
  --from-literal=session_secret=$(openssl rand -base64 32) \
  -n httpd-server 2>/dev/null || true

# Deployment + Service + Route
oc apply -f - <<'EOF'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-fileserver
  namespace: httpd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-fileserver
  template:
    metadata:
      labels:
        app: httpd-fileserver
    spec:
      serviceAccountName: httpd-fileserver
      containers:
        - name: httpd-fileserver
          image: image-registry.openshift-image-registry.svc:5000/httpd-server/httpd-fileserver:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SERVICE_URL
              value: "http://httpd-server.httpd-server.svc.cluster.local:8080"
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
        - name: oauth-proxy
          image: registry.redhat.io/openshift4/ose-oauth-proxy:v4.14
          args:
            - --https-address=:8443
            - --provider=openshift
            - --openshift-service-account=httpd-fileserver
            - --upstream=http://localhost:8080
            - --tls-cert=/etc/tls/private/tls.crt
            - --tls-key=/etc/tls/private/tls.key
            - --cookie-secret-file=/etc/proxy/secrets/session_secret
            - --cookie-refresh=0
            - "--openshift-delegate-urls={\"/\":{\"resource\":\"services\",\"verb\":\"get\",\"namespace\":\"httpd-server\"}}"
          ports:
            - containerPort: 8443
              name: https
          volumeMounts:
            - name: tls
              mountPath: /etc/tls/private
              readOnly: true
            - name: cookie-secret
              mountPath: /etc/proxy/secrets
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: httpd-fileserver-data
        - name: tls
          secret:
            secretName: httpd-server-tls
        - name: cookie-secret
          secret:
            secretName: httpd-proxy-cookie
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-server
  namespace: httpd-server
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: httpd-server-tls
spec:
  selector:
    app: httpd-fileserver
  ports:
    - name: https
      port: 8443
      targetPort: 8443
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: httpd-server
  namespace: httpd-server
spec:
  to:
    kind: Service
    name: httpd-server
  port:
    targetPort: https
  tls:
    termination: reencrypt
EOF

echo "   Waiting for deployment rollout..."
oc rollout status deploy/httpd-fileserver -n httpd-server --timeout=120s
echo "   HTTP file server deployed successfully."
FILESERVER_EOF
done
echo ""

# -----------------------------------------------------------------
# Step 3: Deploy Showroom on hub with student cluster data
#   Generates a hub vars file that appends student cluster details
#   as Showroom Antora attributes. Operators skip (idempotency).
# -----------------------------------------------------------------
if [[ "$DEPLOY_SHOWROOM" == "true" ]]; then
  SHOWROOM_CONFIG="acm-virt-hub-showroom"
  echo "==> Collecting student cluster data for Showroom..."

  # Extract Grafana URL from hub user data (set by ocp4_workload_rhacm_observability)
  GRAFANA_URL=$(grep 'grafana_url:' "$HUB_USER_DATA" 2>/dev/null | head -1 | awk '{print $2}' || echo "")

  {
    cat "$SCRIPT_DIR/acm-virt-hub.yaml"
    echo ""
    echo "# --- deploy.sh runtime: override workloads to Showroom only ---"
    echo "# Operators are already installed; only Showroom needs to run."
    echo "workloads:"
    echo "  - agnosticd.core_workloads.ocp4_workload_showroom"
    echo ""
    echo "# --- deploy.sh runtime: student cluster data for Showroom ---"
    echo "hub_console_url: \"$HUB_CONSOLE_URL\""
    echo "hub_api_url: \"$HUB_API_URL\""
    echo "hub_bastion_hostname: \"$HUB_BASTION\""
    echo "hub_ssh_command: \"ssh student@$HUB_BASTION\""
    echo "num_students: $NUM_STUDENTS"
    if [[ -n "$GRAFANA_URL" ]]; then
      echo "grafana_url: \"$GRAFANA_URL\""
    fi

    for i in $(seq 1 "$NUM_STUDENTS"); do
      s_guid="${BASE_GUID}-s${i}"
      s_data="$OUTPUT_DIR/$s_guid/provision-user-data.yaml"

      if [[ -f "$s_data" ]]; then
        s_console=$(grep 'openshift_console_url:' "$s_data" 2>/dev/null | head -1 | awk '{print $2}' || echo "N/A")
        s_api=$(grep 'openshift_api_url:' "$s_data" 2>/dev/null | head -1 | awk '{print $2}' || echo "N/A")
        s_bastion=$(grep 'bastion_public_hostname:' "$s_data" 2>/dev/null | head -1 | awk '{print $2}' || echo "N/A")
        s_bastion_pass=$(grep 'bastion_ssh_password:' "$s_data" 2>/dev/null | head -1 | awk '{print $2}' || echo "N/A")
        s_bastion_user=$(grep 'bastion_ssh_user_name:' "$s_data" 2>/dev/null | head -1 | awk '{print $2}' || echo "student")

        echo ""
        echo "student_${i}_console_url: \"$s_console\""
        echo "student_${i}_api_url: \"$s_api\""
        echo "student_${i}_bastion_hostname: \"$s_bastion\""
        echo "student_${i}_bastion_ssh_user: \"$s_bastion_user\""
        echo "student_${i}_bastion_ssh_password: \"$s_bastion_pass\""
        echo "student_${i}_ssh_command: \"ssh ${s_bastion_user}@${s_bastion}\""

        s_admin_pass=$(grep 'openshift_cluster_admin_password:' "$s_data" 2>/dev/null | head -1 | awk '{print $2}' || echo "N/A")
        echo "student_${i}_admin_password: \"$s_admin_pass\""

        s_ingress=$(grep 'openshift_cluster_ingress_domain:' "$s_data" 2>/dev/null | head -1 | awk '{print $2}' || echo "N/A")
        echo "student_${i}_ingress_domain: \"$s_ingress\""
      fi
    done
  } > "$VARS_DIR/${SHOWROOM_CONFIG}.yml"

  echo "==> Deploying Showroom on hub with student cluster data..."
  ./bin/agd provision -g "$HUB_GUID" -c "$SHOWROOM_CONFIG" -a "$ACCOUNT"
  echo "Showroom deployed with student cluster variables."
  echo ""

  rm -f "$VARS_DIR/${SHOWROOM_CONFIG}.yml"
fi

# -----------------------------------------------------------------
# Step 4: Generate student-info.txt
# -----------------------------------------------------------------
extract_field() {
  local file="$1" key="$2" default="${3:-N/A}"
  grep "${key}:" "$file" 2>/dev/null | head -1 | awk '{print $2}' || echo "$default"
}

generate_student_info() {
  local info_file="$SCRIPT_DIR/student-info.txt"
  echo "==> Generating deployment info..."

  local hub_data="$OUTPUT_DIR/$HUB_GUID/provision-user-data.yaml"
  local hub_kubeadmin_file="$OUTPUT_DIR/$HUB_GUID/openshift-cluster_${HUB_GUID}_kubeadmin-password"
  local hub_console hub_api hub_bastion hub_bastion_pass hub_bastion_user hub_admin_pass hub_grafana hub_showroom hub_ingress

  if [[ -f "$hub_data" ]]; then
    hub_console=$(extract_field "$hub_data" openshift_console_url)
    hub_api=$(extract_field "$hub_data" openshift_api_url)
    hub_bastion=$(extract_field "$hub_data" bastion_public_hostname)
    hub_bastion_pass=$(extract_field "$hub_data" bastion_ssh_password)
    hub_bastion_user=$(extract_field "$hub_data" bastion_ssh_user_name student)
    hub_ingress=$(extract_field "$hub_data" openshift_cluster_ingress_domain)
    hub_showroom=$(extract_field "$hub_data" lab_ui_url)
    if [[ "$hub_showroom" == "N/A" ]]; then
      hub_showroom=$(extract_field "$hub_data" showroom_primary_view_url)
    fi
    hub_grafana="https://grafana-open-cluster-management-observability.${hub_ingress}"
  fi
  # Hub uses kubeadmin password file; htpasswd admin password may also exist
  if [[ -f "$hub_kubeadmin_file" ]]; then
    hub_admin_pass="$(cat "$hub_kubeadmin_file" 2>/dev/null)"
    hub_admin_user="kubeadmin"
  else
    hub_admin_pass=$(extract_field "$hub_data" openshift_cluster_admin_password)
    hub_admin_user="admin"
  fi

  {
    echo "================================================================"
    echo "  ACM Virtual Machine Management Demo — Deployment Info"
    echo "  Generated: $(date)"
    echo "================================================================"
    echo ""
    echo "================================================================"
    echo "  HUB CLUSTER ACCESS"
    echo "================================================================"
    echo "  Console:   $hub_console"
    echo "  API:       $hub_api"
    echo "  Admin:     ${hub_admin_user} / ${hub_admin_pass}"
    echo "  Bastion:   ssh ${hub_bastion_user}@${hub_bastion}  (password: ${hub_bastion_pass})"
    echo "  oc login:  oc login ${hub_api} -u ${hub_admin_user} -p ${hub_admin_pass}"
    echo "  Showroom:  $hub_showroom"
    echo "  Grafana:   $hub_grafana"
    echo ""

    for i in $(seq 1 "$NUM_STUDENTS"); do
      local s_guid="${BASE_GUID}-s${i}"
      local s_data="$OUTPUT_DIR/$s_guid/provision-user-data.yaml"

      echo "================================================================"
      echo "  STUDENT CLUSTER ${i}  ($s_guid)"
      echo "================================================================"

      if [[ -f "$s_data" ]]; then
        local s_console s_api s_bastion s_bastion_pass s_bastion_user s_admin_pass s_ingress
        s_console=$(extract_field "$s_data" openshift_console_url)
        s_api=$(extract_field "$s_data" openshift_api_url)
        s_bastion=$(extract_field "$s_data" bastion_public_hostname)
        s_bastion_pass=$(extract_field "$s_data" bastion_ssh_password)
        s_bastion_user=$(extract_field "$s_data" bastion_ssh_user_name student)
        s_admin_pass=$(extract_field "$s_data" openshift_cluster_admin_password)
        s_ingress=$(extract_field "$s_data" openshift_cluster_ingress_domain)

        echo "  Console:   $s_console"
        echo "  API:       $s_api"
        echo "  Admin:     admin / $s_admin_pass"
        echo "  Bastion:   ssh ${s_bastion_user}@${s_bastion}  (password: ${s_bastion_pass})"
        echo "  oc login:  oc login $s_api -u admin -p $s_admin_pass"
        echo "  File Srv:  https://httpd-server-httpd-server.${s_ingress}"
        echo "  Type:      SNO (m5zn.metal, bare-metal KVM)"
      else
        echo "  (no data found — cluster may not be deployed yet)"
      fi
      echo ""
    done

    echo "================================================================"
    echo "  QUICK REFERENCE"
    echo "================================================================"
    echo "  Hub oc login:   oc login $hub_api -u $hub_admin_user -p $hub_admin_pass"
    echo "  Showroom:       $hub_showroom"
    echo "  Grafana:        $hub_grafana"
    echo "  Student info:   $info_file"
    echo "  Manifest:       $MANIFEST"
    echo "================================================================"
  } | tee "$info_file"

  echo ""
  echo "Info saved to: $info_file"

  if [[ -d "$DEMO_ROOT" ]]; then
    cp "$info_file" "$DEMO_ROOT/student-info.txt"
    echo "Also copied to: $DEMO_ROOT/student-info.txt"
  fi
}

generate_student_info

echo ""
echo "================================================================"
echo "Deployment complete."
echo "  Hub:      ${HUB_GUID}"
echo "  Students: ${NUM_STUDENTS} (type: ${STUDENT_TYPE})"
echo "  GUIDs:    $(tr '\n' ' ' < "$MANIFEST")"
echo "  Info:     $SCRIPT_DIR/student-info.txt"
echo "================================================================"
