{
 "title": "ACM Right Sizing Openshift Virtualization Dashboard",
 "tags": [
  "acm",
  "right-sizing",
  "virtualization"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(acm_rs_vm:cpu_request, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(acm_rs_vm:cpu_request{cluster=~\"$cluster\"}, namespace)"
    }
   },
   { "name": "aggregation", "label": "Aggregation", "query": "15d,30d" }
  ]
 },
 "panels": [
  {
   "title": "Total CPU Overestimation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(acm_rs_vm:cpu_overestimation{cluster=~\"$cluster\", namespace=~\"$namespace\"} > 0)"
    }
   ]
  },
  {
   "title": "Total CPU Underestimation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(acm_rs_vm:cpu_underestimation{cluster=~\"$cluster\", namespace=~\"$namespace\"} > 0)"
    }
   ]
  },
  {
   "title": "Total Memory Overestimation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(acm_rs_vm:memory_overestimation{cluster=~\"$cluster\", namespace=~\"$namespace\"} > 0)"
    }
   ]
  },
  {
   "title": "Total Memory Underestimation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(acm_rs_vm:memory_underestimation{cluster=~\"$cluster\", namespace=~\"$namespace\"} > 0)"
    }
   ]
  },
  {
   "title": "CPU Overestimation by VM",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "acm_rs_vm:cpu_usage_max_5m{cluster=~\"$cluster\", namespace=~\"$namespace\"} / acm_rs_vm:cpu_request{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
    },
    {
     "expr": "acm_rs_vm:cpu_request{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
    },
    {
     "expr": "quantile_over_time(0.95, acm_rs_vm:cpu_usage_max_5m{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$aggregation])"
    },
    {
     "expr": "acm_rs_vm:cpu_overestimation{cluster=~\"$cluster\", namespace=~\"$namespace\"} > 0"
    }
   ]
  },
  {
   "title": "Memory Overestimation by VM",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "acm_rs_vm:memory_usage_max_5m{cluster=~\"$cluster\", namespace=~\"$namespace\"} / acm_rs_vm:memory_request{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
    },
    {
     "expr": "acm_rs_vm:memory_request{cluster=~\"$cluster\", namespace=~\"$namespace\"}"
    },
    {
     "expr": "quantile_over_time(0.95, acm_rs_vm:memory_usage_max_5m{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$aggregation])"
    },
    {
     "expr": "acm_rs_vm:memory_overestimation{cluster=~\"$cluster\", namespace=~\"$namespace\"} > 0"
    }
   ]
  }
 ]
}